#!/usr/bin/env groovy

//ENV Vars
def TOOLS_NAMESPACE = "4zq6uj-patricksimonian-ocp201-tst-tools"
def DEV_NAMESPACE = "4zq6uj-patricksimonian-ocp201-tst-dev"
def PROD_NAMESPACE = "4zq6uj-patricksimonian-ocp201-tst-prod"


//Pipeline
node {
  stage ('Build Stage'){
      dir ('simple_pipeline') {
        checkout scm
        sh "oc process -f openshift201/templates/template_loki_sample.yaml -p  LOKI_SERVICE_NAME=${LOKI_SERVICE} | oc apply -f - -n ${DEV_NAMESPACE}"
      }
  }
}